// flow-typed signature: dd3915f5e1d9a167c7bed1beebd309f7
// flow-typed version: <<STUB>>/crx_v^3.0.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'crx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'crx/bin/crx' {
  declare module.exports: any;
}

declare module 'crx/coverage/prettify' {
  declare module.exports: any;
}

declare module 'crx/coverage/sorter' {
  declare module.exports: any;
}

declare module 'crx/src/crx' {
  declare module.exports: any;
}

declare module 'crx/src/resolver' {
  declare module.exports: any;
}

// Filename aliases
declare module 'crx/bin/crx.js' {
  declare module.exports: $Exports<'crx/bin/crx'>;
}
declare module 'crx/coverage/prettify.js' {
  declare module.exports: $Exports<'crx/coverage/prettify'>;
}
declare module 'crx/coverage/sorter.js' {
  declare module.exports: $Exports<'crx/coverage/sorter'>;
}
declare module 'crx/src/crx.js' {
  declare module.exports: $Exports<'crx/src/crx'>;
}
declare module 'crx/src/resolver.js' {
  declare module.exports: $Exports<'crx/src/resolver'>;
}
