// flow-typed signature: 42973d9d30becf64408ff313a61ddcb6
// flow-typed version: <<STUB>>/pug-cli_v^1.0.0-alpha6/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pug-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pug-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pug-cli/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pug-cli/index' {
  declare module.exports: $Exports<'pug-cli'>;
}
declare module 'pug-cli/index.js' {
  declare module.exports: $Exports<'pug-cli'>;
}
declare module 'pug-cli/test/index.js' {
  declare module.exports: $Exports<'pug-cli/test/index'>;
}
