// flow-typed signature: af724cafc6e91c9c0255831f2a4c9dbe
// flow-typed version: <<STUB>>/webpack-httpolyglot-server_v^0.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-httpolyglot-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-httpolyglot-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-httpolyglot-server/lib/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-httpolyglot-server/lib/server.js' {
  declare module.exports: $Exports<'webpack-httpolyglot-server/lib/server'>;
}
